server:
    port: 8090
    context-path: #/liuzh/
kafka:
    servers:
          bootstrap: 192.168.1.249:19092,192.168.1.252:19092
    topic:
          helloworld: helloWorld
logging:
    level:
        org:
          springframework: INFO
        com:
          easy:
            study: DEBUG